/* Generated by Together */

package scenario.bienenstock.einfacheUmgebung;
import java.util.HashSet;
import scenario.bienenstock.Koordinate;

public class EinfacherBienenstock extends EinfachesFeld {
    public EinfacherBienenstock(Koordinate pos,
        				 HashSet wBienen,
                         HashSet fBienen,
                         HashSet tBienen,
                         int vID) {
        super(pos,
              wBienen,
              fBienen,
              tBienen);
        /*position = pos;
        wartendeBienen = wBienen;
        fliegendeBienen = fBienen;
        tanzendeBienen = tBienen;*/
        volksID = vID;
    }

    public int gibVolksID() {
        return volksID;
    }

    private int volksID;
}
