/* Generated by Together */

package scenario.bienenstock;
import java.util.LinkedList;

public class TestAgentBlume {
    private boolean hatHonig;
    private LinkedList weg;

    public TestAgentBlume(LinkedList daLang, boolean honig) {
        weg = daLang;
        hatHonig = honig;
    }

    LinkedList gibWeg() {
        return weg;
    }
    boolean besitztHonig() {
        return hatHonig;
    }
    void hatKeinenHonigMehr() {
        hatHonig = false;
    }
    void hatNochHonig() {
        hatHonig = true;
    }
}
