/*
 * Dateiname      : TestAgentBlume.java
 * Erzeugt        : 20. Januar 2005
 * Letzte Änderung: 
 * Autoren        : Philip Funck (mango.3@gmx.de)
 *                  Samuel Walz (felix-kinkowski@gmx.net)
 *                  
 *                  
 *
 * Diese Datei gehört zum Projekt Nereus (http://nereus.berlios.de/).
 * Die erste Version dieser Datei wurde erstellt im Rahmen eines
 * Software-Praktikums von Philip Funck und Samuel Walz am Institut für
 * Intelligente Systeme der Universität Stuttgart unter Betreuung von
 * Dietmar Lippold (dietmar.lippold@informatik.uni-stuttgart.de).
 *
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
/* Generated by Together */

package agents.bienenstock.utils;
import java.util.LinkedList;

/** enthält Informationen über eine Blume */
public class InfoBlumeEinfach {
    /** Zeigt an, ob die Blume noch Nektar hat. */
    private boolean hatNektar;
    /** Weg von der Blume zum Bienenstock     */
    private LinkedList weg;
    
    /**
     * @param daLang Weg zum Bienenstock
     * @param nektar enthält die Blume noch Nektar
     */
    public InfoBlumeEinfach(LinkedList daLang, boolean nektar) {
        weg = daLang;
        hatNektar = nektar;
    }
    
    /**
     * liefert den Weg
     * @return Weg
     */
    public LinkedList gibWeg() {
        return weg;
    }
    /**
     * hat die Blume noch Nektar
     * @return true, falls die Blume noch Nektar enthält.
     */
    public boolean besitztNektar() {
        return hatNektar;
    }
    
    /**
     * setzt die Blume auf: hat kein Nektar mehr
     */
    public void hatKeinenNektarMehr() {
        hatNektar = false;
    }
    /**
     * setzt die Blume auf: hat noch Nektar 
     */
    public void hatNochNektar() {
        hatNektar = true;
    }
}
