/* Generated by Together */

package scenario.bienenstock.einfacheUmgebung;
import java.util.Hashtable;

public class EinfacheKarte {
    public EinfacheKarte(EinfacheBiene selber, Hashtable Felder) {
        selbst = selber;
        spielfeldAusschnitt = Felder;
    }

    public EinfacheBiene gibSelbst() {
        return selbst;
    }

    public Hashtable gibFelder() {
        return spielfeldAusschnitt;
    }

    private EinfacheBiene selbst;

    /**
     * @associates EinfachesFeld
     */
    private Hashtable spielfeldAusschnitt;
}
