/* Generated by Together */

package scenario.bienenstock.einfacheUmgebung;

import scenario.bienenstock.Koordinate;
import scenario.bienenstock.Info;
/**
 * ist das Abbild des Agenten im Szenario.
 * 
 * Dieses Abbild wird verwendet um die Werte der Agenten für etwaige Überprüfungen bereit zu halten.
 * Dadurch werden beeinflussungen der Werte durch den jeweiligen Agenten ausgeschlossen. 
 */
public class EinfacheBiene {
    /**
     * Ist die Nummer der aktuellen Runde.
     */
    private int Rundennummer;

    private String zustand;

    /**
     * ist eine Nummer, die die Biene eindeutig kennzeichnet.
     * Ist identisch mit der Agent-ID die die Agenten im Simulator haben.
     */
    private int bienenID;

    /**
     * ist eine Nummer, die die Zugehörigkeit einer Biene eindeutig kennzeichnet. 
     */
    private int bienenvolkID;
    private Koordinate position;

    /**
     * ist der Code, der vom Agenten benötigt wird um eine Aktion auszuführen. 
     */
    private long aktionsCode;
    private int geladeneHonigmenge;
    private int geladeneNektarmenge;
    private Info information;

    public EinfacheBiene(int runde,
        String zust,
        int eigenID,
        int volkID,
        Koordinate bienePosition,
        long aktCode,
        int gelHonigmenge,
        int gelNektarmenge) {

        Rundennummer = runde;
		zustand = zust;
        bienenID = eigenID;
        bienenvolkID = volkID;
        position = bienePosition;
        aktionsCode = aktCode;
        geladeneHonigmenge = gelHonigmenge;
        geladeneNektarmenge = gelNektarmenge;
        information = null;

    }

    public EinfacheBiene(int runde,
        String zust,
        int eigenID,
        int volkID,
        Koordinate bienePosition,
        long aktCode,
        int gelHonigmenge,
        int gelNektarmenge,
        Info infoObjekt) {

        Rundennummer = runde;
		zustand = zust;
        bienenID = eigenID;
        bienenvolkID = volkID;
        position = bienePosition;
        aktionsCode = aktCode;
        geladeneHonigmenge = gelHonigmenge;
        geladeneNektarmenge = gelNektarmenge;
        information = infoObjekt;
    }

    public int gibRundennummer() {
        return Rundennummer;
    }

    public String gibZustand() {
        return zustand;
    }

    public int gibBienenID() {
        return bienenID;
    }

    public int gibBienenvolkID() {
        return bienenvolkID;
    }

    public Koordinate gibPosition() {
        return position;
    }

    public long gibAktionsCode(){
        return aktionsCode;
    }

    public int gibGeladeneNektarmenge() {
        return geladeneNektarmenge;
    }

    public int gibGeladeneHonigmenge(){
        return geladeneHonigmenge;
    }

    public Info gibInformation() {
        return information;
    }
}
