/* Generated by Together */

package scenario.bienenstock.einfacheUmgebung;
//import scenario.bienenstock.umgebung.Biene;
import scenario.bienenstock.Koordinate;
import java.util.HashSet;
import java.util.Hashtable;
import java.util.HashMap;
public class EinfachesFeld {
    protected Koordinate position;

    /**
     * @associates scenario.bienenstock.einfacheUmgebung.EinfachesFeld 
     */
    protected HashMap nachbarfelder;

    /**
     * @associates java.lang.Integer
     */
    protected HashSet wartendeBienen;

    /**
     * @associates java.lang.Integer
     */
    protected HashSet fliegendeBienen;

    /**
     * @associates java.lang.Integer
     */
    protected HashSet tanzendeBienen;

    public EinfachesFeld(Koordinate pos,
        				 HashSet wBienen,
                         HashSet fBienen,
                         HashSet tBienen) {
        position = pos;
        wartendeBienen = wBienen;
        fliegendeBienen = fBienen;
        tanzendeBienen = tBienen;
    }

    public void setzeNachbarfelder(HashMap nachbarn) {
        nachbarfelder = nachbarn;
    }

    public Koordinate gibPosition() {
        return position;
    }

    public HashMap gibNachbarfelder () {
        return nachbarfelder;
    }

    /**
     * @associates java.lang.Integer
     */
    public HashSet gibIDsWartendeBienen() {
        return (HashSet)wartendeBienen.clone();
    }

    /**
     * @associates java.lang.Integer
     */
    public HashSet gibIDsFliegendeBienen() {
        return (HashSet)fliegendeBienen.clone();
    }

    /**
     * @associates java.lang.Integer
     */
    public HashSet gibIDsTanzendeBienen() {
        return (HashSet)tanzendeBienen.clone();
    }
}
