/* Generated by Together */

package scenario.bienenstock.statistik;

import java.util.ArrayList;
import scenario.bienenstock.umgebung.Bienenstock;
import scenario.bienenstock.umgebung.Bienenstock;
import scenario.bienenstock.Koordinate;

/**
 * speichert die Werte der Biene zu jeder Runde.
 *
 * Zählt bei jedem Eintragen von Werten der Biene intern die Rundennummer hoch.
 * @author Philip Funck
 * @author Samuel Walz
 */
public class StatistikBienenstock {
    public StatistikBienenstock(int bieneID) {
    }

    public int gelagerterHonig(int runde) {
        return 0;
    }

    public int gelagerterNektar(int runde) {
        return 0;
    }

    public Koordinate position(int runde) {
        return null;
    }

    /**
     * liest von der zu beobachtenden Biene die Werte ein und speichert diese in einem neuen Eintrag.
     */
    public void rundenwerteSetzen(    ) {
    }

    public int volksID() {
        return 0;
    }

    private ArrayList werteliste;
    private Bienenstock zuBeobachtenderStock;
    private int volksID;

    public class werteBienenstock {
        private int gelagerterHonig;
        private int gelagerterNektar;
    }
}
