/* Generated by Together */

package scenario.bienenstock.einfacheUmgebung;

import java.util.HashSet;
import scenario.bienenstock.Koordinate;
public class EinfacherPlatz extends EinfachesFeld {
    public EinfacherPlatz(Koordinate pos,
        				 HashSet wBienen,
                         HashSet fBienen,
                         HashSet tBienen) {
        super(pos,
              wBienen,
              fBienen,
              tBienen);
        /*position = pos;
        wartendeBienen = wBienen;
        fliegendeBienen = fBienen;
        tanzendeBienen = tBienen;*/
    }
}
