

/* Generated by Together */
package scenario.bienenstock;

import simulator.AbstractAgent;
import simulator.AbstractAgentOptional;
import simulator.AbstractScenarioHandler;
import utils.Id;

public abstract class AbstrakteBiene extends AbstractAgent {
    protected int volksID;
    public AbstrakteBiene() {
    super();
    }
    public AbstrakteBiene(String name, AbstractScenarioHandler handler) {
        super(name, handler);
        }
    public AbstrakteBiene(Id id, String name) {
        super(id, name);
        }
    public abstract void setHandler (AbstractScenarioHandler bHandler);
    public abstract boolean aktionscodeSetzen(long neuerAktionscode);
    public abstract int gibVolksID();
}
